### ISSUE TITLE
Send a group of photos or videos as an album.

### ISSUE THREAD

**Issue by InspectorDue** [dhvcc/VK-TG-transfer-bot#10]
Telegram API [let](https://core.telegram.org/bots/api#sendmediagroup) send group of photos or videos.

**Comment by dhvcc** [comment]
> Telegram API [let](https://core.telegram.org/bots/api#sendmediagroup) send group of photos or videos.

Yeah it was just like a reminder to refactor code
Anyways, new message reference feature needs the attachments to be sent separately :)
