### ISSUE TITLE
Backwards TG->VK support

### ISSUE THREAD

**Issue by dhvcc** [dhvcc/VK-TG-transfer-bot#3]
I don't think that's really necessary, but it would be a nice feature to have TG to VK support

**Comment by InspectorDue** [comment]
What do you mean?
Sending messages via Telegram or getting messages from Telegram in VK
I think the first one. 
And how it should look?
Like I send command `/send_message`
Then I choose the conversation, then I send some text or/and add some attachments. Then I press the button `Send` or if i change my mind `Cancel`.

**Comment by dhvcc** [comment]
So this should work in reverse to the current functionality
Currently VK bot longpolls and watches for any new message in some convo
Then the bot parses VK message and sends TG equivalent to TG convo

I will try to make better docs with examples

**Comment by lolmaus** [comment]
Would really love to see this feature.

**Comment by dhvcc** [comment]
@lolmaus I'll try to find some time to look at this issue later, though this will not be soon

**Comment by dhvcc** [comment]
I don't really think this is a priority as the main goal of the repo to migrate from VK. I'll reply to this issue if I find time and I'll implement it. This codebase needs rewriting, it's so messy
